name: Coderco Secrets CI

on:
  workflow_dispatch:   # only runs when you click "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use secrets
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "The secret is $MY_SECRET"







